export enum EventType {
    ORDER_STARTED = 'ORDER_STARTED',
    ORDER_REJECTED = 'ORDER_REJECTED',
    ORDER_RESOLVED = 'ORDER_RESOLVED',

    SUPPLY_STARTED = 'SUPPLY_STARTED',
    SUPPLY_REJECTED = 'SUPPLY_REJECTED',
    SUPPLY_RESOLVED = 'SUPPLY_RESOLVED',

    DELIVERY_STARTED = 'DELIVERY_STARTED',
    DELIVERY_REJECTED = 'DELIVERY_REJECTED',
    DELIVERY_RESOLVED = 'DELIVERY_RESOLVED'
}
