export enum EventType {
    ORDER_STARTED = 'ORDER_STARTED',
    ORDER_UNKNOWN_ERROR = 'ORDER_UNKNOWN_ERROR',
    ORDER_RESOLVED = 'ORDER_RESOLVED',

    SUPPLY_STARTED = 'SUPPLY_STARTED',
    SUPPLY_UNKNOWN_ERROR = 'SUPPLY_UNKNOWN_ERROR',
    SUPPLY_RESOLVED = 'SUPPLY_RESOLVED',

    DELIVERY_STARTED = 'DELIVERY_STARTED',
    DELIVERY_UNKNOWN_ERROR = 'DELIVERY_UNKNOWN_ERROR',
    DELIVERY_RESOLVED = 'DELIVERY_RESOLVED'
}
